[package]
name = "bevy_arangodb_derive"
version = "0.1.0"
edition.workspace = true

[lib]
proc-macro = true

[dependencies]
syn = { workspace = true, features = ["derive", "parsing"] }
quote = { workspace = true }
proc-macro2 = { workspace = true }
proc-macro-crate = "3.3.0"
ctor.workspace = true
